//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_End.RandomColoursServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RandomColoursServiceReference.IRandomColoursService")]
    public interface IRandomColoursService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomColoursService/GenerateRandomColour", ReplyAction="http://tempuri.org/IRandomColoursService/GenerateRandomColourResponse")]
        System.Drawing.Color GenerateRandomColour(System.Drawing.Color[] usedColours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomColoursService/GenerateRandomColour", ReplyAction="http://tempuri.org/IRandomColoursService/GenerateRandomColourResponse")]
        System.Threading.Tasks.Task<System.Drawing.Color> GenerateRandomColourAsync(System.Drawing.Color[] usedColours);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRandomColoursServiceChannel : Front_End.RandomColoursServiceReference.IRandomColoursService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RandomColoursServiceClient : System.ServiceModel.ClientBase<Front_End.RandomColoursServiceReference.IRandomColoursService>, Front_End.RandomColoursServiceReference.IRandomColoursService {
        
        public RandomColoursServiceClient() {
        }
        
        public RandomColoursServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RandomColoursServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RandomColoursServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RandomColoursServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Drawing.Color GenerateRandomColour(System.Drawing.Color[] usedColours) {
            return base.Channel.GenerateRandomColour(usedColours);
        }
        
        public System.Threading.Tasks.Task<System.Drawing.Color> GenerateRandomColourAsync(System.Drawing.Color[] usedColours) {
            return base.Channel.GenerateRandomColourAsync(usedColours);
        }
    }
}
